import Head from 'next/head'
import About from '../components/About'
import Navbar from '../components/Navbar'
import Main from './../components/Main'

export default function Home () {
  return (
    <div>
      <Head>
        <title>Muhammad | Frontend Developer </title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Navbar />
      <Main />
      <About />
    </div>
  )
}
